Repository woowa-techcamp-2021/cashbook-03, pull requests merged in 2021-08, with the labels that each got.

#40 [#13] feat: 메인 탭 스타일링
  client/src/components/MainTab/MainTab.scss
  client/src/components/MainTab/MainTab.ts
  client/src/pages/Main.ts
  client/src/public/styles/index.scss
  client/src/public/styles/reset.scss
Labels: FE

#41 [#8] 결제수단 API, [#42] 회원가입시 기본 결제수단 등록
  server/src/app.ts
  server/src/controllers/payment.ts
  server/src/controllers/user.ts
  server/src/passport/github.ts
  server/src/repository/payment.ts
  server/src/repository/user.ts
  server/src/service/payment.ts
  server/src/service/user.ts
Labels: BE

#43 [#9] 지출 내역 API 완료
  server/src/controllers/account.ts
  server/src/repository/account.ts
  server/src/service/account.ts
Labels: BE

#46 [#14] 달력 탭 스타일링
  client/src/components/Calendar/Calendar.scss
  client/src/components/Calendar/Calendar.ts
  client/src/components/SignHeader/SignHeader.ts
  client/src/components/SignMain/SignMain.ts
  client/src/containers/CalendarContainer.ts
  client/src/containers/SignContainer.ts
  client/src/pages/Calendar.ts
  client/src/pages/Login.ts
  client/src/public/styles/index.scss
  client/src/public/styles/mixins.scss
Labels: FE

#47 [#18] feat: 메인탭 기능추가
  client/src/App.ts
  client/src/components/MainTab/MainTab.scss
  client/src/components/MainTab/MainTab.ts
  client/src/components/SignMain/SignMain.scss
  client/src/components/SignMain/SignMain.ts
  client/src/containers/MainTabContainer.ts
  client/src/pages/Main.ts
  client/src/store.ts
  client/src/utils/api/account.ts
  client/src/utils/api/category.ts
  client/src/utils/api/payment.ts
Labels: FE

#49 FE 구조 리팩토링 / 새 구조에 맞게 MainTab 수정
  client/src/App.ts
  client/src/Router.ts
  client/src/components/Calendar/Calendar.ts
  client/src/components/MainTab/MainTab.ts
  client/src/containers/CalendarContainer.ts
  client/src/containers/HeaderContainer.ts
  client/src/containers/MainTabContainer.ts
  client/src/containers/SignContainer.ts
  client/src/pages/Signup.ts
  client/src/store.ts
  client/src/store/category.ts
  client/src/store/date.ts
  client/src/store/index.ts
  client/src/store/payment.ts
  client/src/store/user.ts
  client/src/utils/Observable/index.ts
  client/src/utils/View/index.ts
Labels: FE, Refactoring

#50 [#48] db 오류 수정 및 자잘한 버그 수정
  client/src/components/MainTab/MainTab.scss
  client/src/containers/HeaderContainer.ts
  client/src/utils/View/index.ts
  server/src/controllers/account.ts
  server/src/controllers/auth.ts
  server/src/loaders/sequelize.ts
  server/src/model/category.ts
  server/src/model/index.ts
  server/src/repository/account.ts
Labels: BE, bug

#52 [#51] 프론트 구조 통합 후 리팩토링
  client/src/App.ts
  client/src/containers/MainTabContainer.ts
  client/src/store/account.ts
  client/src/store/index.ts
  client/src/utils/api/account.ts
Labels: FE

#55 attribute 업데이트 방식 리팩토링
  client/src/utils/View/index.ts
Labels: FE, Refactoring

#59 [#58] wip: 메인 account ui
  client/src/components/Account/Account.scss
  client/src/components/Account/Account.ts
  client/src/pages/Main.ts
  client/src/public/styles/index.scss
Labels: FE

#61 [#20] 달력 탭 기능
  client/src/App.ts
  client/src/Router.ts
  client/src/components/Calendar/Calendar.ts
  client/src/components/Calendar/CalendarContent/CalendarContent.ts
  client/src/components/Calendar/CalendarContent/sub-components/index.ts
  client/src/components/Calendar/helpers/index.ts
  client/src/containers/CalendarContainer.ts
  client/src/utils/View/index.ts
  server/src/model/index.ts
Labels: FE

#62 [#48] 레디스 적용
  client/src/App.ts
  client/src/Router.ts
  client/src/components/Account/Account.ts
  server/.env.sample
  server/package-lock.json
  server/package.json
  server/src/config/index.ts
  server/src/config/redis-config.ts
  server/src/loaders/session.ts
Labels: BE

#64 [#63] Be/bug 수정
  client/src/containers/MainTabContainer.ts
  server/.env.sample
  server/package.json
  server/src/config/redis-config.ts
  server/src/loaders/session.ts
  server/src/repository/account.ts
Labels: BE, FE

#66 [#63] bug: front에서 서버로 갈때 url 수정 (http)
  client/src/containers/SignContainer.ts
  client/src/utils/api/client.ts
Labels: BE

#68 [#21] 통계 탭 도넛그래프 오른쪽 부분 완성
  client/src/components/MainChart/CategoryList.ts
  client/src/components/MainChart/MainChart.scss
  client/src/components/MainChart/MainChart.ts
  client/src/containers/MainChartContainer.ts
  client/src/pages/Statistics.ts
  client/src/public/styles/index.scss
Labels: FE

#70 [#21] 도넛 차트 완성
  client/src/components/MainChart/Donut.ts
  client/src/components/MainChart/MainChart.scss
  client/src/components/MainChart/MainChart.ts
  client/src/containers/MainChartContainer.ts
  client/src/pages/Statistics.ts
Labels: FE

#74 [#22] 통계탭 기능 완성
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/components/LineChart/LineChart.scss
  client/src/components/LineChart/LineChart.ts
  client/src/components/MainChart/CategoryList.ts
  client/src/components/MainChart/MainChart.scss
  client/src/components/MainChart/MainChart.ts
  client/src/components/StatAccountList/StatAccountList.scss
  client/src/components/StatAccountList/StatAccountList.ts
  client/src/containers/MainChartContainer.ts
  client/src/pages/Statistics.ts
  client/src/public/styles/index.scss
  client/src/store/category.ts
  client/src/utils/api/account.ts
  server/package-lock.json
  server/src/controllers/account.ts
  server/src/repository/account.ts
  server/src/service/account.ts
Labels: FE, Refactoring

#72 [#71]Fe/refacto
  client/src/App.ts
  client/src/Router.ts
  client/src/components/Account/Account.scss
  client/src/components/Account/Account.ts
  client/src/components/Account/AccountItem.ts
  client/src/components/MainTab/MainTab.scss
  client/src/components/MainTab/MainTab.ts
  client/src/containers/AccountContainer.ts
  client/src/containers/MainTabContainer.ts
  client/src/pages/Error.ts
  client/src/pages/Main.ts
  client/src/public/images/modify.png
  client/src/public/styles/error.scss
  client/src/public/styles/index.scss
  client/src/store/account.ts
  client/src/utils/api/account.ts
  server/src/controllers/account.ts
  server/src/model/payment.ts
  server/src/repository/account.ts
  server/src/repository/payment.ts
  server/src/service/account.ts
Labels: FE, Refactoring, bug

#77 서버 요청 시 로딩 UI
  client/src/App.ts
  client/src/components/Header/Header.ts
  client/src/index.html
  client/src/public/styles/font.scss
  client/src/public/styles/index.scss
  client/src/public/styles/loader.scss
  client/src/utils/api/client.ts
  client/src/utils/loader/index.ts
Labels: FE

#78 bug: 카테고리 순서 보장되게 변경, 드롭다운 z-index 수정
  client/src/components/MainTab/MainTab.scss
  server/src/model/category.ts
Labels: BE, FE, bug

#80 [#79] Fe/refacto
  client/src/components/Account/Account.scss
  client/src/components/Account/Account.ts
  client/src/containers/MainTabContainer.ts
  client/src/public/images/favicon.ico
  client/src/public/images/modify.png
  client/webpack.config.js
  server/src/controllers/payment.ts
  server/src/repository/payment.ts
Labels: bug, FE

#84 [#20] wip: 날짜 클릭시 하단에 내역 표시
  client/src/components/Calendar/Calendar.scss
  client/src/components/CalendarAccountList/CalendarAccountList.scss
  client/src/components/CalendarAccountList/CalendarAccountList.ts
  client/src/containers/CalendarContainer.ts
  client/src/public/styles/index.scss
Labels: FE

#85 [#20] bug: 결제수단 없을때 '수입'으로 처리
  client/src/components/CalendarAccountList/CalendarAccountList.ts
Labels: bug, FE
