Repository woowa-techcamp-2021/cashbook-03, pull requests merged in 2021-07, with the labels that each got.

#24 기본 보일러 플레이트 적용
  .gitignore
  client/.babelrc
  client/.eslintrc.json
  client/.prettierrc
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/src/App.ts
  client/src/index.html
  client/webpack.config.js
  server/.eslintrc.json
  server/.prettierrc
  server/package.json
Labels: BE, FE

#25 [#10] feat: 프론트 기본 프레임 완성
  client/package-lock.json
  client/package.json
  client/src/App.ts
  client/src/Router.ts
  client/src/components/Header.ts
  client/src/containers/HeaderContainer.ts
  client/src/index.html
  client/src/pages/Calendar.ts
  client/src/pages/Error.ts
  client/src/pages/Main.ts
  client/src/pages/Statistics.ts
  client/src/store.ts
  client/src/utils/View/index.ts
  client/src/utils/api/client.ts
Labels: FE

#26 [#2] BE 기본 구조 완료
  .gitignore
  server/.env.sample
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/cors-config.ts
  server/src/config/db-config.ts
  server/src/config/index.ts
  server/src/controllers/account.ts
  server/src/controllers/category.ts
  server/src/controllers/index.ts
  server/src/controllers/payment.ts
  server/src/controllers/user.ts
  server/src/error/index.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/loaders/sequelize.ts
  server/src/model/account.ts
  server/src/model/category.ts
  server/src/model/index.ts
  server/src/model/payment.ts
  server/src/model/user.ts
  server/src/repository/account.ts
  server/src/repository/category.ts
  server/src/repository/payment.ts
  server/src/repository/user.ts
  server/src/service/account.ts
  server/src/service/category.ts
  server/src/service/payment.ts
  server/src/service/user.ts
  server/tsconfig.json
Labels: BE

#30 헤더 스타일링
  client/src/components/Header.ts
  client/src/components/Header/Header.scss
  client/src/components/Header/Header.ts
  client/src/containers/HeaderContainer.ts
  client/src/pages/Main.ts
  client/src/public/styles/font.scss
  client/src/public/styles/index.scss
  client/src/public/styles/mixins.scss
  client/src/public/styles/reset.scss
  client/src/public/styles/woowahan-cashbook-icons.woff
  client/src/public/styles/woowahan-cashbook-icons.woff2
  client/src/public/svg/calendar.svg
  client/src/public/svg/chart.svg
  client/src/public/svg/check.svg
  client/src/public/svg/chevron-down.svg
  client/src/public/svg/chevron-left.svg
  client/src/public/svg/chevron-right.svg
  client/src/public/svg/close.svg
  client/src/public/svg/file-text.svg
  client/webpack.config.js
Labels: FE

#31 헤더 FE 기능
  client/src/Router.ts
  client/src/components/Header/Header.scss
  client/src/components/Header/Header.ts
  client/src/containers/HeaderContainer.ts
  client/src/pages/Calendar.ts
  client/src/pages/Statistics.ts
  client/src/public/styles/variables.scss
  client/webpack.config.js
Labels: FE

#33 [#16] 로그인, 회원가입 페이지 스타일링
  client/src/App.ts
  client/src/components/Header/Header.scss
  client/src/components/Header/Header.ts
  client/src/components/SignHeader/SignHeader.scss
  client/src/components/SignHeader/SignHeader.ts
  client/src/components/SignMain/SignMain.scss
  client/src/components/SignMain/SignMain.ts
  client/src/containers/SignContainer.ts
  client/src/pages/Login.ts
  client/src/pages/Signup.ts
  client/src/public/images/github.png
  client/src/public/styles/index.scss
  client/src/public/styles/variables.scss
Labels: FE

#32 [#3] 백엔드 로그인 구현
  server/package-lock.json
  server/package.json
  server/src/config/index.ts
  server/src/controllers/auth.ts
  server/src/controllers/index.ts
  server/src/controllers/user.ts
  server/src/error/index.ts
  server/src/loaders/index.ts
  server/src/loaders/session.ts
  server/src/model/user.ts
  server/src/passport/github.ts
  server/src/passport/index.ts
  server/src/passport/local.ts
  server/src/repository/user.ts
  server/src/service/user.ts
Labels: BE

#36 [#35] bug: req.user 버그 수정
  server/src/controllers/account.ts
  server/src/types/express.d.ts
  server/tsconfig.json
Labels: BE, bug

#39 [#38] 로그인 서버와 프론트 병합
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/App.ts
  client/src/components/Header/Header.ts
  client/src/components/SignMain/SignMain.scss
  client/src/components/SignMain/SignMain.ts
  client/src/containers/HeaderContainer.ts
  client/src/containers/SignContainer.ts
  client/src/utils/api/auth.ts
  client/webpack.config.js
  server/.env.sample
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/index.ts
  server/src/controllers/auth.ts
  server/src/controllers/user.ts
  server/src/passport/github.ts
  server/src/passport/local.ts
  server/src/repository/user.ts
  server/src/service/payment.ts
Labels: BE, FE, bug
